name: Generate Types Dry Run

on:
  workflow_dispatch:

jobs:
  generate-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 📥
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Ensures submodules are also checked out

      - name: Setup Node.js 🌐
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Update Git Submodules 🔄
        run: |
          make update-cosmos  # Fixed typo here

      - name: Install Dependencies 🧶
        run: |
          cd v2
          yarn install
          yarn symlink

      - name: Build Project 🏗️
        run: |
          cd v2
          yarn build
          yarn symlink

      - name: Types Generation 🛠
        run: |         
          cd v2

          # Generate types and interfaces
          pushd workflows/generate-types
          yarn generate:types
          yarn generate:interfaces
          popd

          # Build types
          pushd packages/types
          yarn build
          popd

          # Build interfaces
          pushd packages/interfaces
          yarn build
          popd

          # Generate and build code for chain registry
          pushd packages/chain-registry
          yarn codegen
          yarn build
          popd

          cd ..

          # check changes
          git add .
          if ! git diff --staged --quiet; then
            echo "GIT_RESULT=Changes to commit and/or publish." >> $GITHUB_ENV
          else
            echo "GIT_RESULT=No changes to commit." >> $GITHUB_ENV
          fi

      - name: Git Result
        run: |
          echo $GIT_RESULT